#dataset: IMDB-MULTI
#epochs: 300
#batch_size: 64
#capsule_dimensions: 8
#capsule_num: 10
#dropout: 0.7
#theta: 0.1
#weight_decay: 0
#devices: [1]
#lr: 0.01
## lr 0.01  93.5
#lr_decay_step_size: 250
##threshold: 0.4

dataset: IMDB-MULTI
epochs: 300
batch_size: 16
capsule_dimensions: 8
capsule_num: 15
dropout: 0.7
theta: 0.1
weight_decay: 1e-5
devices: [1]
lr: 0.001
lr_decay_step_size: 250
k: 5

