dataset: NCI1
epochs: 600
batch_size: 128
capsule_dimensions: 8
capsule_num: 15
dropout: 0
theta: 0.2
#weight_decay: 0.0001
weight_decay: 1e-5
devices: [0]
lr: 0.01
lr_decay_step_size: 250
k: 5
k2: 3