dataset: COLLAB
epochs: 400
batch_size: 256
capsule_dimensions: 6
capsule_num: 15
dropout: 0.7
theta: 0.1
#weight_decay: 0.0001
weight_decay: 1e-5
devices: [0]
lr: 0.005
lr_decay_step_size: 100
k: 3
k2: 3
num_iterations: 3
num_gcn_layers: 3
# patience: 100