dataset: ENZYMES
epochs: 1000
batch_size: 128
capsule_dimensions: 8
capsule_num: 15
dropout: 0.3
theta: 0.1
#weight_decay: 0.0001
weight_decay: 1e-5
devices: [0]
lr: 0.005
lr_decay_step_size: 500
k: 3